name: api_call
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:

  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: 8.1.1
  dio: 4.0.6
  equatable: 2.0.5
  pull_to_refresh: 2.0.0
  sqflite: 2.0.3+1
  connectivity_plus: 2.3.7
  shared_preferences: 2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
